<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Adnan Jaber" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 1, SDS348 Fall 2020</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project1/">Project 1, SDS348 Fall 2020</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         October 18, 2020 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="r-markdown" class="section level2">
<h2>R Markdown</h2>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>When you click the <strong>Knit</strong> button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:</p>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(ggplot2)
library(ggrepel)
library(tidyr)
library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ tibble  3.0.3     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.5.0
## ✓ purrr   0.3.4</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>co2emissions &lt;- read_csv(&quot;co2_emissions_tonnes_per_person.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   country = col_character()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<pre class="r"><code>avgincome&lt;- read_csv(&quot;income_per_person_gdppercapita_ppp_inflation_adjusted.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   country = col_character()
## )
## See spec(...) for full column specifications.</code></pre>
<pre class="r"><code>avgenergyuse &lt;- read_csv(&quot;energy_use_per_person.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   country = col_character()
## )
## See spec(...) for full column specifications.</code></pre>
<pre class="r"><code>head(avgincome)</code></pre>
<pre><code>## # A tibble: 6 x 242
##   country `1800` `1801` `1802` `1803` `1804` `1805` `1806` `1807` `1808` `1809`
##   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Afghan…    603    603    603    603    603    603    603    603    603    603
## 2 Albania    667    667    667    667    667    668    668    668    668    668
## 3 Algeria    715    716    717    718    719    720    721    722    723    724
## 4 Andorra   1200   1200   1200   1200   1210   1210   1210   1210   1220   1220
## 5 Angola     618    620    623    626    628    631    634    637    640    642
## 6 Antigu…    757    757    757    757    757    757    757    758    758    758
## # … with 231 more variables: `1810` &lt;dbl&gt;, `1811` &lt;dbl&gt;, `1812` &lt;dbl&gt;,
## #   `1813` &lt;dbl&gt;, `1814` &lt;dbl&gt;, `1815` &lt;dbl&gt;, `1816` &lt;dbl&gt;, `1817` &lt;dbl&gt;,
## #   `1818` &lt;dbl&gt;, `1819` &lt;dbl&gt;, `1820` &lt;dbl&gt;, `1821` &lt;dbl&gt;, `1822` &lt;dbl&gt;,
## #   `1823` &lt;dbl&gt;, `1824` &lt;dbl&gt;, `1825` &lt;dbl&gt;, `1826` &lt;dbl&gt;, `1827` &lt;dbl&gt;,
## #   `1828` &lt;dbl&gt;, `1829` &lt;dbl&gt;, `1830` &lt;dbl&gt;, `1831` &lt;dbl&gt;, `1832` &lt;dbl&gt;,
## #   `1833` &lt;dbl&gt;, `1834` &lt;dbl&gt;, `1835` &lt;dbl&gt;, `1836` &lt;dbl&gt;, `1837` &lt;dbl&gt;,
## #   `1838` &lt;dbl&gt;, `1839` &lt;dbl&gt;, `1840` &lt;dbl&gt;, `1841` &lt;dbl&gt;, `1842` &lt;dbl&gt;,
## #   `1843` &lt;dbl&gt;, `1844` &lt;dbl&gt;, `1845` &lt;dbl&gt;, `1846` &lt;dbl&gt;, `1847` &lt;dbl&gt;,
## #   `1848` &lt;dbl&gt;, `1849` &lt;dbl&gt;, `1850` &lt;dbl&gt;, `1851` &lt;dbl&gt;, `1852` &lt;dbl&gt;,
## #   `1853` &lt;dbl&gt;, `1854` &lt;dbl&gt;, `1855` &lt;dbl&gt;, `1856` &lt;dbl&gt;, `1857` &lt;dbl&gt;,
## #   `1858` &lt;dbl&gt;, `1859` &lt;dbl&gt;, `1860` &lt;dbl&gt;, `1861` &lt;dbl&gt;, `1862` &lt;dbl&gt;,
## #   `1863` &lt;dbl&gt;, `1864` &lt;dbl&gt;, `1865` &lt;dbl&gt;, `1866` &lt;dbl&gt;, `1867` &lt;dbl&gt;,
## #   `1868` &lt;dbl&gt;, `1869` &lt;dbl&gt;, `1870` &lt;dbl&gt;, `1871` &lt;dbl&gt;, `1872` &lt;dbl&gt;,
## #   `1873` &lt;dbl&gt;, `1874` &lt;dbl&gt;, `1875` &lt;dbl&gt;, `1876` &lt;dbl&gt;, `1877` &lt;dbl&gt;,
## #   `1878` &lt;dbl&gt;, `1879` &lt;dbl&gt;, `1880` &lt;dbl&gt;, `1881` &lt;dbl&gt;, `1882` &lt;dbl&gt;,
## #   `1883` &lt;dbl&gt;, `1884` &lt;dbl&gt;, `1885` &lt;dbl&gt;, `1886` &lt;dbl&gt;, `1887` &lt;dbl&gt;,
## #   `1888` &lt;dbl&gt;, `1889` &lt;dbl&gt;, `1890` &lt;dbl&gt;, `1891` &lt;dbl&gt;, `1892` &lt;dbl&gt;,
## #   `1893` &lt;dbl&gt;, `1894` &lt;dbl&gt;, `1895` &lt;dbl&gt;, `1896` &lt;dbl&gt;, `1897` &lt;dbl&gt;,
## #   `1898` &lt;dbl&gt;, `1899` &lt;dbl&gt;, `1900` &lt;dbl&gt;, `1901` &lt;dbl&gt;, `1902` &lt;dbl&gt;,
## #   `1903` &lt;dbl&gt;, `1904` &lt;dbl&gt;, `1905` &lt;dbl&gt;, `1906` &lt;dbl&gt;, `1907` &lt;dbl&gt;,
## #   `1908` &lt;dbl&gt;, `1909` &lt;dbl&gt;, …</code></pre>
<pre class="r"><code>head(co2emissions)</code></pre>
<pre><code>## # A tibble: 6 x 220
##   country `1800` `1801` `1802` `1803` `1804` `1805` `1806` `1807` `1808` `1809`
##   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Afghan…     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## 2 Albania     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## 3 Algeria     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## 4 Andorra     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## 5 Angola      NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## 6 Antigu…     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## # … with 209 more variables: `1810` &lt;dbl&gt;, `1811` &lt;dbl&gt;, `1812` &lt;dbl&gt;,
## #   `1813` &lt;dbl&gt;, `1814` &lt;dbl&gt;, `1815` &lt;dbl&gt;, `1816` &lt;dbl&gt;, `1817` &lt;dbl&gt;,
## #   `1818` &lt;dbl&gt;, `1819` &lt;dbl&gt;, `1820` &lt;dbl&gt;, `1821` &lt;dbl&gt;, `1822` &lt;dbl&gt;,
## #   `1823` &lt;dbl&gt;, `1824` &lt;dbl&gt;, `1825` &lt;dbl&gt;, `1826` &lt;dbl&gt;, `1827` &lt;dbl&gt;,
## #   `1828` &lt;dbl&gt;, `1829` &lt;dbl&gt;, `1830` &lt;dbl&gt;, `1831` &lt;dbl&gt;, `1832` &lt;dbl&gt;,
## #   `1833` &lt;dbl&gt;, `1834` &lt;dbl&gt;, `1835` &lt;dbl&gt;, `1836` &lt;dbl&gt;, `1837` &lt;dbl&gt;,
## #   `1838` &lt;dbl&gt;, `1839` &lt;dbl&gt;, `1840` &lt;dbl&gt;, `1841` &lt;dbl&gt;, `1842` &lt;dbl&gt;,
## #   `1843` &lt;dbl&gt;, `1844` &lt;dbl&gt;, `1845` &lt;dbl&gt;, `1846` &lt;dbl&gt;, `1847` &lt;dbl&gt;,
## #   `1848` &lt;dbl&gt;, `1849` &lt;dbl&gt;, `1850` &lt;dbl&gt;, `1851` &lt;dbl&gt;, `1852` &lt;dbl&gt;,
## #   `1853` &lt;dbl&gt;, `1854` &lt;dbl&gt;, `1855` &lt;dbl&gt;, `1856` &lt;dbl&gt;, `1857` &lt;dbl&gt;,
## #   `1858` &lt;dbl&gt;, `1859` &lt;dbl&gt;, `1860` &lt;dbl&gt;, `1861` &lt;dbl&gt;, `1862` &lt;dbl&gt;,
## #   `1863` &lt;dbl&gt;, `1864` &lt;dbl&gt;, `1865` &lt;dbl&gt;, `1866` &lt;dbl&gt;, `1867` &lt;dbl&gt;,
## #   `1868` &lt;dbl&gt;, `1869` &lt;dbl&gt;, `1870` &lt;dbl&gt;, `1871` &lt;dbl&gt;, `1872` &lt;dbl&gt;,
## #   `1873` &lt;dbl&gt;, `1874` &lt;dbl&gt;, `1875` &lt;dbl&gt;, `1876` &lt;dbl&gt;, `1877` &lt;dbl&gt;,
## #   `1878` &lt;dbl&gt;, `1879` &lt;dbl&gt;, `1880` &lt;dbl&gt;, `1881` &lt;dbl&gt;, `1882` &lt;dbl&gt;,
## #   `1883` &lt;dbl&gt;, `1884` &lt;dbl&gt;, `1885` &lt;dbl&gt;, `1886` &lt;dbl&gt;, `1887` &lt;dbl&gt;,
## #   `1888` &lt;dbl&gt;, `1889` &lt;dbl&gt;, `1890` &lt;dbl&gt;, `1891` &lt;dbl&gt;, `1892` &lt;dbl&gt;,
## #   `1893` &lt;dbl&gt;, `1894` &lt;dbl&gt;, `1895` &lt;dbl&gt;, `1896` &lt;dbl&gt;, `1897` &lt;dbl&gt;,
## #   `1898` &lt;dbl&gt;, `1899` &lt;dbl&gt;, `1900` &lt;dbl&gt;, `1901` &lt;dbl&gt;, `1902` &lt;dbl&gt;,
## #   `1903` &lt;dbl&gt;, `1904` &lt;dbl&gt;, `1905` &lt;dbl&gt;, `1906` &lt;dbl&gt;, `1907` &lt;dbl&gt;,
## #   `1908` &lt;dbl&gt;, `1909` &lt;dbl&gt;, …</code></pre>
<pre class="r"><code>head(avgenergyuse)</code></pre>
<pre><code>## # A tibble: 6 x 57
##   country `1960` `1961` `1962` `1963` `1964` `1965` `1966` `1967` `1968` `1969`
##   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Albania     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## 2 Algeria     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## 3 Angola      NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## 4 Antigu…     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## 5 Argent…     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## 6 Armenia     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
## # … with 46 more variables: `1970` &lt;dbl&gt;, `1971` &lt;dbl&gt;, `1972` &lt;dbl&gt;,
## #   `1973` &lt;dbl&gt;, `1974` &lt;dbl&gt;, `1975` &lt;dbl&gt;, `1976` &lt;dbl&gt;, `1977` &lt;dbl&gt;,
## #   `1978` &lt;dbl&gt;, `1979` &lt;dbl&gt;, `1980` &lt;dbl&gt;, `1981` &lt;dbl&gt;, `1982` &lt;dbl&gt;,
## #   `1983` &lt;dbl&gt;, `1984` &lt;dbl&gt;, `1985` &lt;dbl&gt;, `1986` &lt;dbl&gt;, `1987` &lt;dbl&gt;,
## #   `1988` &lt;dbl&gt;, `1989` &lt;dbl&gt;, `1990` &lt;dbl&gt;, `1991` &lt;dbl&gt;, `1992` &lt;dbl&gt;,
## #   `1993` &lt;dbl&gt;, `1994` &lt;dbl&gt;, `1995` &lt;dbl&gt;, `1996` &lt;dbl&gt;, `1997` &lt;dbl&gt;,
## #   `1998` &lt;dbl&gt;, `1999` &lt;dbl&gt;, `2000` &lt;dbl&gt;, `2001` &lt;dbl&gt;, `2002` &lt;dbl&gt;,
## #   `2003` &lt;dbl&gt;, `2004` &lt;dbl&gt;, `2005` &lt;dbl&gt;, `2006` &lt;dbl&gt;, `2007` &lt;dbl&gt;,
## #   `2008` &lt;dbl&gt;, `2009` &lt;dbl&gt;, `2010` &lt;dbl&gt;, `2011` &lt;dbl&gt;, `2012` &lt;dbl&gt;,
## #   `2013` &lt;dbl&gt;, `2014` &lt;dbl&gt;, `2015` &lt;dbl&gt;</code></pre>
</div>
<div id="introduction-ive-chosen-three-datasets-for-my-project-and-found-these-datasets-through-gapminder.com.-one-that-has-the-average-co2-emissions-per-person-in-tonnes-by-country-and-year-one-that-had-the-average-income-per-person-in-international-dollars-by-country-and-year-and-another-that-had-the-average-total-energy-consumption-per-person-by-country-and-year.-i-chose-these-datasets-due-to-my-curiosity-about-the-impact-richer-countries-have-on-global-emissions-and-i-thought-it-would-be-interesting-to-look-at-the-correlation-between-energy-consumption-and-capital-as-well.-i-believe-to-see-a-positive-correlation-between-income-per-person-and-co2-emissions-because-i-believe-that-people-with-more-money-have-access-to-things-that-emit-more-co2.-i-also-believe-that-there-will-be-a-positive-correation-between-income-and-energy-consumption." class="section level2">
<h2>Introduction: I've chosen three datasets for my project and found these datasets through 'gapminder.com'. One that has the average CO2 emissions per person (in tonnes) by country and year, one that had the average income per person (in international dollars) by country and year, and another that had the average total energy consumption per person by country and year. I chose these datasets due to my curiosity about the impact richer countries have on global emissions and I thought it would be interesting to look at the correlation between energy consumption and capital as well. I believe to see a positive correlation between income per person and CO2 emissions because I believe that people with more money have access to things that emit more CO2. I also believe that there will be a positive correation between income and energy consumption.</h2>
</div>
<div id="tidying-my-data" class="section level1">
<h1>Tidying my data:</h1>
<pre class="r"><code>#My datasets were not tidy so I tidyed them before joining them

avgincomes &lt;- avgincome %&gt;% pivot_longer(c(2:242), names_to = &quot;year&quot;, values_to= &quot;avg income per person&quot;)
head(avgincomes)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   country     year  `avg income per person`
##   &lt;chr&gt;       &lt;chr&gt;                   &lt;dbl&gt;
## 1 Afghanistan 1800                      603
## 2 Afghanistan 1801                      603
## 3 Afghanistan 1802                      603
## 4 Afghanistan 1803                      603
## 5 Afghanistan 1804                      603
## 6 Afghanistan 1805                      603</code></pre>
<pre class="r"><code>avgco2&lt;- co2emissions
avgCO2use&lt;- avgco2 %&gt;% pivot_longer(c(2:220), names_to = &quot;year&quot;, values_to= &quot;avg co2 consumption per person&quot;)
head(avgCO2use)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   country     year  `avg co2 consumption per person`
##   &lt;chr&gt;       &lt;chr&gt;                            &lt;dbl&gt;
## 1 Afghanistan 1800                                NA
## 2 Afghanistan 1801                                NA
## 3 Afghanistan 1802                                NA
## 4 Afghanistan 1803                                NA
## 5 Afghanistan 1804                                NA
## 6 Afghanistan 1805                                NA</code></pre>
<pre class="r"><code>averageEnergyUSE &lt;- avgenergyuse %&gt;% pivot_longer(c(2:57), names_to = &quot;year&quot;, values_to= &quot;avg energy consumption per person&quot;)
#These pivot longer functions allow year to be a column rather than a row for each data set. This makes the data easier to work with.
head(averageEnergyUSE)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   country year  `avg energy consumption per person`
##   &lt;chr&gt;   &lt;chr&gt;                               &lt;dbl&gt;
## 1 Albania 1960                                   NA
## 2 Albania 1961                                   NA
## 3 Albania 1962                                   NA
## 4 Albania 1963                                   NA
## 5 Albania 1964                                   NA
## 6 Albania 1965                                   NA</code></pre>
<pre class="r"><code>#I joined my data in two steps, I used left join both times because I wanted to match all the data sets based on &quot;country&quot; and &quot;year
joiningpt1 &lt;- left_join(avgCO2use, avgincomes, by=c(&quot;country&quot;, &quot;year&quot;))
head(joiningpt1)</code></pre>
<pre><code>## # A tibble: 6 x 4
##   country     year  `avg co2 consumption per person` `avg income per person`
##   &lt;chr&gt;       &lt;chr&gt;                            &lt;dbl&gt;                   &lt;dbl&gt;
## 1 Afghanistan 1800                                NA                     603
## 2 Afghanistan 1801                                NA                     603
## 3 Afghanistan 1802                                NA                     603
## 4 Afghanistan 1803                                NA                     603
## 5 Afghanistan 1804                                NA                     603
## 6 Afghanistan 1805                                NA                     603</code></pre>
<pre class="r"><code>totaldata &lt;- left_join(joiningpt1, averageEnergyUSE, by=c(&quot;country&quot;, &quot;year&quot;))
totaldata &lt;- left_join(joiningpt1, averageEnergyUSE, by=c(&quot;country&quot;, &quot;year&quot;))
head(totaldata)</code></pre>
<pre><code>## # A tibble: 6 x 5
##   country   year  `avg co2 consumption… `avg income per p… `avg energy consumpt…
##   &lt;chr&gt;     &lt;chr&gt;                 &lt;dbl&gt;              &lt;dbl&gt;                 &lt;dbl&gt;
## 1 Afghanis… 1800                     NA                603                    NA
## 2 Afghanis… 1801                     NA                603                    NA
## 3 Afghanis… 1802                     NA                603                    NA
## 4 Afghanis… 1803                     NA                603                    NA
## 5 Afghanis… 1804                     NA                603                    NA
## 6 Afghanis… 1805                     NA                603                    NA</code></pre>
</div>
<div id="making-my-data-nice-to-work-with" class="section level1">
<h1>Making my data nice to work with:</h1>
<pre class="r"><code>totaldata %&gt;% summarize_all(funs(sum(is.na(.))))</code></pre>
<pre><code>## Warning: `funs()` is deprecated as of dplyr 0.8.0.
## Please use a list of either functions or lambdas: 
## 
##   # Simple named list: 
##   list(mean = mean, median = median)
## 
##   # Auto named with `tibble::lst()`: 
##   tibble::lst(mean, median)
## 
##   # Using lambdas
##   list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_warnings()` to see where this warning was generated.</code></pre>
<pre><code>## # A tibble: 1 x 5
##   country  year `avg co2 consumption … `avg income per p… `avg energy consumpti…
##     &lt;int&gt; &lt;int&gt;                  &lt;int&gt;              &lt;int&gt;                  &lt;int&gt;
## 1       0     0                  24009                219                  36128</code></pre>
<pre class="r"><code>noNAtotaldata &lt;- na.omit(totaldata)</code></pre>
</div>
<div id="i-wanted-to-get-the-number-of-nas-per-column-because-the-datasets-did-not-align-very-well-by-year.-there-were-24009-nas-for-avg-co2-consumption-per-person-219-nas-for-avg-income-per-person-and-36128-nas-for-avg-energy-consumption-per-person-decided-to-make-a-new-data-set-without-nas" class="section level1">
<h1>I wanted to get the number of NAs per column because the datasets did not align very well by year. There were 24009 NAs for &quot;avg co2 consumption per person&quot;, 219 NAs for &quot;avg income per person&quot;, and 36128 NAs for &quot;avg energy consumption per person&quot; &amp; decided to make a new data set without NAs</h1>
</div>
<div id="from-this-dataset-without-nas-i-decided-to-get-the-mean-avg-energy-consumption-per-person-avg-co2-emission-per-person-and-avg-income-per-person-by-country-for-all-time-data-fom-every-year-is-averaged-together" class="section level1">
<h1>From this dataset without NAs I decided to get the mean &quot;avg energy consumption per person&quot;, &quot;avg co2 emission per person&quot;, and &quot;avg income per person&quot; by country for all time (data fom every year is averaged together)</h1>
<pre class="r"><code>totalaverages &lt;- noNAtotaldata%&gt;%group_by(country)%&gt;% summarise_at(vars(-year), funs(mean(., na.rm=TRUE)))

head(totalaverages)</code></pre>
<pre><code>## # A tibble: 6 x 4
##   country      `avg co2 consumption … `avg income per p… `avg energy consumptio…
##   &lt;chr&gt;                         &lt;dbl&gt;              &lt;dbl&gt;                   &lt;dbl&gt;
## 1 Albania                       1.71               5559.                    748.
## 2 Algeria                       2.91              10835                     805.
## 3 Angola                        0.721              4910                     508.
## 4 Antigua and…                  5.20              22420                    1682 
## 5 Argentina                     3.87              14730.                   1589.
## 6 Armenia                       1.67               4536                     896</code></pre>
<pre class="r"><code>#I decided that I wanted to make every column of data on similar scales, so I made each one into a percentile with 100 being the country that had the highest value in each column. I then removed the non-percentile columns.
totalpercentiles &lt;- totalaverages %&gt;% mutate(&#39;co2_pctile&#39; = ntile(`avg co2 consumption per person`, 100)) %&gt;% mutate(&#39;income_pctile&#39; = ntile(`avg income per person`, 100)) %&gt;% mutate(&#39;energyuse_pctile&#39; = ntile(`avg energy consumption per person`, 100)) %&gt;% select(-&quot;avg co2 consumption per person&quot;) %&gt;% select(-&quot;avg income per person&quot;) %&gt;% select(-&quot;avg energy consumption per person&quot;)

head(totalpercentiles) </code></pre>
<pre><code>## # A tibble: 6 x 4
##   country             co2_pctile income_pctile energyuse_pctile
##   &lt;chr&gt;                    &lt;int&gt;         &lt;int&gt;            &lt;int&gt;
## 1 Albania                     35            31               37
## 2 Algeria                     45            49               38
## 3 Angola                      22            29               24
## 4 Antigua and Barbuda         57            67               54
## 5 Argentina                   49            57               52
## 6 Armenia                     34            26               40</code></pre>
</div>
<div id="exploring-my-data" class="section level1">
<h1>Exploring my data:</h1>
<pre class="r"><code>#I grouped my data by country and arranged it in descending order of &quot;co2_pctile&quot; so I could get a quick idea about if my predictions at the beginning of my project were correct or not. From a quick look, it would appear as if they were (ex:Qatar is in the 100th percentile for avg income per person, avg energy use per person, and avg co2 emissions per person)
totalpercentiles %&gt;% group_by(country) %&gt;% arrange(desc(co2_pctile)) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
## # Groups:   country [6]
##   country              co2_pctile income_pctile energyuse_pctile
##   &lt;chr&gt;                     &lt;int&gt;         &lt;int&gt;            &lt;int&gt;
## 1 Qatar                       100           100              100
## 2 United Arab Emirates         99            99               97
## 3 Luxembourg                   98            96               98
## 4 Brunei                       97            98               91
## 5 Bahrain                      96            91               99
## 6 Kuwait                       95            97               96</code></pre>
<pre class="r"><code>#I wanted to get an idea of where the United States ranks (which percentile) in each of the categories  
totalpercentiles %&gt;% filter(country== &quot;United States&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 4
##   country       co2_pctile income_pctile energyuse_pctile
##   &lt;chr&gt;              &lt;int&gt;         &lt;int&gt;            &lt;int&gt;
## 1 United States         93            90               94</code></pre>
<pre class="r"><code>noNAdataframe&lt;- data.frame(noNAtotaldata)</code></pre>
</div>
<div id="i-was-curious-about-the-number-of-years-that-the-u.s.-had-recorded-data-for.-from-this-i-found-that-the-u.s.-had-data-recorded-for-56-years-after-removing-all-nas-from-our-dataset." class="section level1">
<h1>I was curious about the number of years that the U.S. had recorded data for. From this I found that the U.S. had data recorded for 56 years after removing all NAs from our dataset.</h1>
<pre class="r"><code>noNAdataframe %&gt;% group_by(country==&quot;United States&quot;) %&gt;% summarise(n())</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   `country == &quot;United States&quot;` `n()`
##   &lt;lgl&gt;                        &lt;int&gt;
## 1 FALSE                         5861
## 2 TRUE                            56</code></pre>
<pre class="r"><code>datasummary &lt;- noNAdataframe %&gt;% group_by(country) %&gt;% summarize(mean_co2emission=mean(avg.co2.consumption.per.person), mean_income=mean(avg.income.per.person), mean_energyuse= mean(avg.energy.consumption.per.person),sd_co2emission=sd(avg.co2.consumption.per.person), sd_income=sd(avg.income.per.person), sd_energyuse= sd(avg.energy.consumption.per.person))</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre class="r"><code>#The standard deviation columns give us the average standard deviation for each category, from all recorded years per country. 

head(datasummary)</code></pre>
<pre><code>## # A tibble: 6 x 7
##   country mean_co2emission mean_income mean_energyuse sd_co2emission sd_income
##   &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 Albania            1.71        5559.           748.          0.713     2316.
## 2 Algeria            2.91       10835            805.          0.545     1524.
## 3 Angola             0.721       4910            508.          0.323     1019.
## 4 Antigu…            5.20       22420           1682           0.402     3449.
## 5 Argent…            3.87       14730.          1589.          0.392     2268.
## 6 Armenia            1.67        4536            896           1.14      2170.
## # … with 1 more variable: sd_energyuse &lt;dbl&gt;</code></pre>
</div>
<div id="i-wanted-to-get-some-summary-stats-about-the-mean-and-standard-deviations-for-co2-emissions-incomes-and-energy-use-world-wide.-from-this-i-found-that-the-world-wide-average-co2-emissions-per-person-per-year-averaged-from-all-recorded-years-is-4.96425-tonnes-the-world-wide-average-income-per-person-per-year-averaged-from-all-recorded-years-is-14252.3-international-dollars-and-that-the-world-wide-average-energy-use-per-person-per-year-averaged-from-all-recorded-years-is-1867.6-units." class="section level1">
<h1>I wanted to get some summary stats about the mean and standard deviations for co2 emissions, incomes, and energy use world-wide. From this I found that the world wide average co2 emissions per person per year, averaged from all recorded years, is 4.96425 tonnes, the world wide average income per person per year, averaged from all recorded years, is 14252.3 international dollars, and that the world wide average energy use per person per year, averaged from all recorded years, is 1867.6 units.</h1>
<pre class="r"><code>datasummary %&gt;% summary()</code></pre>
<pre><code>##    country          mean_co2emission    mean_income       mean_energyuse   
##  Length:168         Min.   : 0.05857   Min.   :   569.1   Min.   :   12.4  
##  Class :character   1st Qu.: 0.72075   1st Qu.:  3675.4   1st Qu.:  476.0  
##  Mode  :character   Median : 2.58077   Median :  8720.0   Median :  991.4  
##                     Mean   : 4.96425   Mean   : 14252.3   Mean   : 1867.6  
##                     3rd Qu.: 6.79057   3rd Qu.: 18007.9   3rd Qu.: 2472.8  
##                     Max.   :52.47955   Max.   :112427.3   Max.   :15437.0  
##  sd_co2emission      sd_income         sd_energyuse    
##  Min.   : 0.0020   Min.   :   24.08   Min.   :   0.75  
##  1st Qu.: 0.1925   1st Qu.:  764.50   1st Qu.:  69.16  
##  Median : 0.6048   Median : 2100.58   Median : 218.38  
##  Mean   : 1.2821   Mean   : 4071.62   Mean   : 454.45  
##  3rd Qu.: 1.6350   3rd Qu.: 5241.77   3rd Qu.: 537.84  
##  Max.   :15.3987   Max.   :36970.77   Max.   :4530.08</code></pre>
<pre class="r"><code>#I then filtered out the United States so I could compare our country to the world wide averages.
datasummary %&gt;% filter(country==&quot;United States&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 7
##   country mean_co2emission mean_income mean_energyuse sd_co2emission sd_income
##   &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 United…             19.4      35420.          7421.           1.77    10859.
## # … with 1 more variable: sd_energyuse &lt;dbl&gt;</code></pre>
<pre class="r"><code>19.40714/4.96425 #CO2 Emissions</code></pre>
<pre><code>## [1] 3.90938</code></pre>
<pre class="r"><code>35419.64/14252.3  #Income</code></pre>
<pre><code>## [1] 2.485188</code></pre>
<pre class="r"><code>7421.25/1867.6  #Energy Use</code></pre>
<pre><code>## [1] 3.973683</code></pre>
</div>
<div id="from-this-we-see-that-the-us-has-an-average-all-time-co2-emission-per-person-per-year-that-is-3.90938-times-greater-than-the-world-wide-averagean-average-all-time-income-per-person-per-year-that-is-2.485188-times-greater-than-the-world-wide-average-and-an-average-all-energy-use-per-person-per-year-that-is-3.973683-times-greater-than-the-world-wide-average." class="section level1">
<h1>From this we see that the US has an average all time CO2 emission per person per year that is 3.90938 times greater than the world-wide average,an average all time income per person per year that is 2.485188 times greater than the world-wide average, and an average all energy use per person per year that is 3.973683 times greater than the world-wide average.</h1>
</div>
<div id="from-our-totalpercentiles-data-set-we-already-know-that-the-us-is-in-the-93rd-percentile-for-all-time-co2-emissions-per-person-90th-percentile-for-all-time-income-per-person-and-94th-percentile-for-energy-use-per-person." class="section level1">
<h1>From our &quot;totalpercentiles&quot; data set we already know that the US is in the 93rd percentile for all time CO2 emissions per person, 90th percentile for all time income per person, and 94th percentile for energy use per person.</h1>
<pre class="r"><code>totalpercentiles %&gt;% filter(country== &quot;United States&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 4
##   country       co2_pctile income_pctile energyuse_pctile
##   &lt;chr&gt;              &lt;int&gt;         &lt;int&gt;            &lt;int&gt;
## 1 United States         93            90               94</code></pre>
<pre class="r"><code>#I was then curious about the difference between the averaged overall mean for each category compared to the median mean of each category
datasummary  %&gt;% summarise(median(mean_income), mean(mean_income), median(mean_co2emission), mean(mean_co2emission), median(mean_energyuse), mean(mean_energyuse))</code></pre>
<pre><code>## # A tibble: 1 x 6
##   `median(mean_in… `mean(mean_inco… `median(mean_co… `mean(mean_co2e…
##              &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1             8720           14252.             2.58             4.96
## # … with 2 more variables: `median(mean_energyuse)` &lt;dbl&gt;,
## #   `mean(mean_energyuse)` &lt;dbl&gt;</code></pre>
</div>
<div id="i-found-that-the-overall-mean-of-each-category-was-nearly-double-for-the-median-of-each-category.-this-tells-us-that-some-countries-hav-avg-co2-emissions-avg-incomes-and-avg-energy-use-per-person-that-are-much-greater-than-most-other-countries-in-the-world." class="section level1">
<h1>I found that the overall mean of each category was nearly double for the median of each category. This tells us that some countries hav avg co2 emissions, avg incomes, and avg energy use per person, that are much greater than most other countries in the world.</h1>
</div>
<div id="i-then-wanted-to-get-the-sds-for-each-column-of-co2-emissions-income-and-energy-use." class="section level1">
<h1>I then wanted to get the SDs for each column of CO2 Emissions, Income, and Energy Use.</h1>
<pre class="r"><code>datasummary %&gt;% summarise(sd(mean_co2emission), sd(mean_income), sd(mean_energyuse)) </code></pre>
<pre><code>## # A tibble: 1 x 3
##   `sd(mean_co2emission)` `sd(mean_income)` `sd(mean_energyuse)`
##                    &lt;dbl&gt;             &lt;dbl&gt;                &lt;dbl&gt;
## 1                   6.79            17174.                2248.</code></pre>
</div>
<div id="i-found-the-sd-between-each-countrys-overall-mean-co2-emissions-per-person-to-be-6.792879-the-sd-between-each-countrys-overall-mean-income-per-person-to-be-17174.02-and-the-sd-between-each-countrys-overall-energy-use-per-person-to-be-17174.02" class="section level1">
<h1>I found the sd between each country's overall mean co2 emissions per person to be 6.792879, the sd between each country's overall mean income per person to be 17174.02, and the sd between each country's overall energy use per person to be 17174.02</h1>
</div>
<div id="i-was-then-interested-in-comparing-the-countries-with-the-max-mean-and-min-mean-for-each-of-the-categories.-returned-to-datasummary-dataset-in-order-to-do-my-comparison-in-units-rather-than-percentiles" class="section level1">
<h1>I was then interested in comparing the countries with the max mean and min mean for each of the categories. (returned to 'datasummary' dataset in order to do my comparison in units rather than percentiles)</h1>
<pre class="r"><code>datasummary  %&gt;% filter(mean_co2emission== max(mean_co2emission))  </code></pre>
<pre><code>## # A tibble: 1 x 7
##   country mean_co2emission mean_income mean_energyuse sd_co2emission sd_income
##   &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 Qatar               52.5     112427.         15437.           15.2    34309.
## # … with 1 more variable: sd_energyuse &lt;dbl&gt;</code></pre>
<pre class="r"><code>datasummary  %&gt;% filter(mean_co2emission== min(mean_co2emission))</code></pre>
<pre><code>## # A tibble: 1 x 7
##   country mean_co2emission mean_income mean_energyuse sd_co2emission sd_income
##   &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 Ethiop…           0.0586         764           479.         0.0173      200.
## # … with 1 more variable: sd_energyuse &lt;dbl&gt;</code></pre>
<pre class="r"><code>datasummary  %&gt;% filter(mean_income== max(mean_income))  </code></pre>
<pre><code>## # A tibble: 1 x 7
##   country mean_co2emission mean_income mean_energyuse sd_co2emission sd_income
##   &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 Qatar               52.5     112427.         15437.           15.2    34309.
## # … with 1 more variable: sd_energyuse &lt;dbl&gt;</code></pre>
<pre class="r"><code>datasummary  %&gt;% filter(mean_income== min(mean_income))</code></pre>
<pre><code>## # A tibble: 1 x 7
##   country mean_co2emission mean_income mean_energyuse sd_co2emission sd_income
##   &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 Mozamb…            0.149        569.           489.         0.0968      231.
## # … with 1 more variable: sd_energyuse &lt;dbl&gt;</code></pre>
<pre class="r"><code>datasummary  %&gt;% filter(mean_energyuse== max(mean_energyuse))  </code></pre>
<pre><code>## # A tibble: 1 x 7
##   country mean_co2emission mean_income mean_energyuse sd_co2emission sd_income
##   &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 Qatar               52.5     112427.         15437.           15.2    34309.
## # … with 1 more variable: sd_energyuse &lt;dbl&gt;</code></pre>
<pre class="r"><code>datasummary  %&gt;% filter(mean_energyuse== min(mean_energyuse))</code></pre>
<pre><code>## # A tibble: 1 x 7
##   country mean_co2emission mean_income mean_energyuse sd_co2emission sd_income
##   &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 Lesotho             1.01       1962.           12.4         0.0212      113.
## # … with 1 more variable: sd_energyuse &lt;dbl&gt;</code></pre>
</div>
<div id="i-found-that-the-country-with-the-max-all-time-mean-co2emission-per-person-per-year-is-qatar-the-country-with-the-min-all-time-mean-co2emission-per-person-per-year-is-ethiopia-the-country-with-the-max-all-time-mean-income-per-person-per-year-is-qatar-the-country-with-the-min-all-time-mean-income-per-person-per-year-is-mozambique-the-country-with-the-max-all-time-energy-use-per-person-per-year-is-qatar-and-that-the-country-with-the-min-all-time-energy-use-per-person-per-year-is-lesotho." class="section level1">
<h1>I found that the country with the max all time mean co2emission per person per year is Qatar, the country with the min all time mean co2emission per person per year is Ethiopia, the country with the max all time mean income per person per year is Qatar, the country with the min all time mean income per person per year is Mozambique, the country with the max all time energy use per person per year is Qatar, and that the country with the min all time energy use per person per year is Lesotho.</h1>
<div id="quick-look-at-the-correlations-between-numeric-variables" class="section level2">
<h2>Quick look at the correlations between numeric variables:</h2>
<pre class="r"><code>datasummary %&gt;%summarize(cor(mean_co2emission, mean_energyuse, use=&quot;pair&quot;))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `cor(mean_co2emission, mean_energyuse, use = &quot;pair&quot;)`
##                                                   &lt;dbl&gt;
## 1                                                 0.951</code></pre>
<pre class="r"><code>datasummary %&gt;%summarize(cor(mean_co2emission, mean_income, use=&quot;pair&quot;))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `cor(mean_co2emission, mean_income, use = &quot;pair&quot;)`
##                                                &lt;dbl&gt;
## 1                                              0.894</code></pre>
<pre class="r"><code>datasummary %&gt;%summarize(cor(mean_income, mean_energyuse, use=&quot;pair&quot;))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `cor(mean_income, mean_energyuse, use = &quot;pair&quot;)`
##                                              &lt;dbl&gt;
## 1                                            0.847</code></pre>
<pre class="r"><code>#I first looked at these correlations, because I was not super interested in my &quot;SD&quot; variables. I found that they each had strong positive correlations with one another.

cormatrix &lt;- datasummary %&gt;% select_if(is.numeric) %&gt;% cor(use=&quot;pair&quot;)

tidymatrix &lt;- cormatrix  %&gt;% as.data.frame %&gt;% rownames_to_column(&quot;var1&quot;) %&gt;%
pivot_longer(-1,names_to=&quot;var2&quot;,values_to=&quot;correlation&quot;)</code></pre>
</div>
</div>
<div id="plot-1-correlation-heat-map" class="section level1">
<h1>Plot 1, Correlation Heat Map:</h1>
</div>
<div id="from-my-correlation-heat-map-you-can-see-that-when-any-one-numeric-variable-is-paired-with-any-other-given-numeric-variable-there-is-a-strong-positive-correlation-between-the-two.-this-tells-us-that-when-one-thing-increase-the-other-does-as-well-generally.-what-our-sd-variables-tell-us-is-that-the-countries-that-have-the-highest-overall-mean-co2-emission-energy-use-and-income-also-saw-great-jumps-in-these-categories-from-year-to-year-or-from-there-lowest-to-highest-points." class="section level1">
<h1>From my correlation heat map you can see that when any one numeric variable is paired with any other given numeric variable, there is a strong, positive correlation between the two. This tells us that when one thing increase, the other does as well, generally. What our &quot;sd&quot; variables tell us, is that the countries that have the highest overall mean co2 emission, energy use, and income, also saw great jumps in these categories from year to year, or from there lowest to highest points.</h1>
<pre class="r"><code>tidymatrix %&gt;% ggplot(aes(var1,var2,fill=correlation)) +geom_tile() +scale_fill_gradient2(low=&quot;red&quot;,mid=&quot;white&quot;,high=&quot;blue&quot;) +geom_text(aes(label=round(correlation,2)),color = &quot;black&quot;, size = 4) +theme(axis.text.x = element_text(angle = 90, hjust=1)) + coord_fixed()</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="plot-2" class="section level1">
<h1>Plot 2:</h1>
</div>
<div id="in-this-scatterplot-below-i-wanted-to-compare-average-income-per-person-and-average-co2-emissions-per-person-and-felt-as-if-the-best-way-to-do-that-would-be-as-percentiles.-this-plot-shows-that-a-country-that-is-at-a-higher-percentile-in-income-per-person-will-most-likely-be-at-a-higher-percentile-in-co2-emissions-per-person.-i-added-a-best-fit-line-to-show-the-strength-of-the-relationship." class="section level1">
<h1>In this scatterplot below, I wanted to compare average income per person and average CO2 emissions per person and felt as if the best way to do that would be as percentiles. This plot shows that a country that is at a higher percentile in income per person, will most likely be at a higher percentile in CO2 emissions per person. I added a best fit line to show the strength of the relationship.</h1>
<pre class="r"><code>ggplot(data = totalpercentiles, aes(x = income_pctile, y = co2_pctile, color=country)) + geom_point() + scale_x_continuous(breaks = seq(0,100,by = 5)) + ggtitle(&quot;Income Percentile vs CO2 Emission Percentile by Country&quot;)  + labs(y=&quot;Avg CO2 Emission Per Person by Country(Percentile)&quot;, x = &quot;Avg Income Per Person by Country(Percentile)&quot;) + theme(legend.position = &quot;none&quot;) + geom_smooth(aes(group = 1), size = 2, method = &quot;lm&quot;, se = FALSE) </code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="plot-3" class="section level1">
<h1>Plot 3:</h1>
</div>
<div id="below-i-made-a-bar-plot-that-shows-the-world-wide-average-co2-emissions-per-person-by-year-to-show-the-way-that-the-emissions-have-changed-year-to-year.-i-also-included-a-backdrop-behind-the-bar-plots-of-the-points-by-country-that-make-up-this-data.-there-are-easily-noticable-outliers-much-greater-than-the-world-wide-average.-due-to-this-i-was-required-to-adjust-the-y-axis-to-make-the-bars-more-visible." class="section level1">
<h1>Below, I made a bar plot that shows the world wide average CO2 emissions per person by year to show the way that the emissions have changed year to year. I also included a backdrop behind the bar plots of the points, by country that make up this data. There are easily noticable outliers much greater than the world wide average. Due to this, I was required to adjust the Y-axis to make the bars more visible.</h1>
<pre class="r"><code>ggplot(noNAdataframe, aes(year,avg.co2.consumption.per.person, fill=year)) + geom_point(aes(fill=country), shape=&quot;.&quot;, color=&quot;darkblue&quot;)+ geom_bar(stat=&quot;summary&quot;, aes(year,avg.co2.consumption.per.person), fun = &quot;mean&quot;) + geom_errorbar(stat=&quot;summary&quot;, width= .2) + xlim(1960,2015) + ylim(0,10)+ scale_x_discrete(breaks = seq(1960, 2015,by = 10))+labs(y=&quot;Avg CO2 Emission Per Person (Tonnes)&quot;, x = &quot;Year&quot;)+ theme_light() + theme(legend.position = &quot;none&quot;) + ggtitle(&quot;Change in Avg CO2 Emission per Person (Worldwide) Over Time&quot;)  </code></pre>
<pre><code>## Scale for &#39;x&#39; is already present. Adding another scale for &#39;x&#39;, which will
## replace the existing scale.</code></pre>
<pre><code>## Warning: Removed 1029 rows containing non-finite values (stat_summary).

## Warning: Removed 1029 rows containing non-finite values (stat_summary).</code></pre>
<pre><code>## No summary function supplied, defaulting to `mean_se()`</code></pre>
<pre><code>## Warning: Removed 1029 rows containing missing values (geom_point).</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="pca" class="section level1">
<h1>PCA:</h1>
<pre class="r"><code>#For this I scaled my data and rid it of unwanted variables.
PCdata&lt;- datasummary %&gt;% select(-c(country, sd_co2emission, sd_income, sd_energyuse)) %&gt;% scale() %&gt;%prcomp()
#Allows us to see the variance each pc is responsible for
PCdata</code></pre>
<pre><code>## Standard deviations (1, .., p=3):
## [1] 1.6717365 0.4032793 0.2065499
## 
## Rotation (n x k) = (3 x 3):
##                        PC1        PC2        PC3
## mean_co2emission 0.5879695 -0.2224087 -0.7777058
## mean_income      0.5656327  0.8003483  0.1987517
## mean_energyuse   0.5782314 -0.5567558  0.5963820</code></pre>
<pre class="r"><code>#I then performed PCA by giving a correlation matrix to eigen
eig1 &lt;- datasummary %&gt;% select(-c(country, sd_co2emission, sd_income, sd_energyuse)) %&gt;% cor() %&gt;% eigen()
#Allows us to see the eigen values and makes a matrix
eig1</code></pre>
<pre><code>## eigen() decomposition
## $values
## [1] 2.79470296 0.16263418 0.04266286
## 
## $vectors
##            [,1]       [,2]       [,3]
## [1,] -0.5879695  0.2224087  0.7777058
## [2,] -0.5656327 -0.8003483 -0.1987517
## [3,] -0.5782314  0.5567558 -0.5963820</code></pre>
<pre class="r"><code>#Looked at the variance in my data that each PC is responsible for
summary(PCdata)</code></pre>
<pre><code>## Importance of components:
##                           PC1     PC2     PC3
## Standard deviation     1.6717 0.40328 0.20655
## Proportion of Variance 0.9316 0.05421 0.01422
## Cumulative Proportion  0.9316 0.98578 1.00000</code></pre>
<pre class="r"><code>datasummary %&gt;% select(mean_co2emission, mean_income, mean_energyuse) %&gt;% cor</code></pre>
<pre><code>##                  mean_co2emission mean_income mean_energyuse
## mean_co2emission        1.0000000   0.8939037      0.9505010
## mean_income             0.8939037   1.0000000      0.8466413
## mean_energyuse          0.9505010   0.8466413      1.0000000</code></pre>
</div>
<div id="we-saw-that-pc-one-was-responsible-for-93.16-of-the-variance-and-pc2-for-5.4-of-the-variance.-for-this-reason-i-choose-these-two-to-make-my-visualizations-only-really-needed-pc1-but-multiple-makes-the-visualizations-more-satisfying" class="section level1">
<h1>We saw that PC one was responsible for 93.16% of the variance and PC2 for 5.4% of the variance. For this reason, I choose these two to make my visualizations (only really needed PC1 but multiple makes the visualizations more satisfying)</h1>
</div>
<div id="pca-visualizations" class="section level1">
<h1>PCA Visualizations:</h1>
</div>
<div id="the-plot-shows-that-pc1-is-good-at-explaining-all-of-the-variables-while-pc2-is-only-good-at-explaining-mean-income." class="section level1">
<h1>The plot shows that PC1 is good at explaining all of the variables, while PC2 is only good at explaining mean income.</h1>
<pre class="r"><code>PCdata$rotation[,1:2]%&gt;%as.data.frame%&gt;%rownames_to_column%&gt;%ggplot()+geom_hline(aes(yintercept=0),lty=2)+ geom_vline(aes(xintercept=0),lty=2)+ylab(&quot;PC2&quot;)+xlab(&quot;PC1&quot;)+
geom_segment(aes(x=0,y=0,xend=PC1,yend=PC2),arrow=arrow(),col=&quot;red&quot;)+
geom_label(aes(x=PC1*1.1,y=PC2*1.1,label=rowname))</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
